[backend]
working_directory = "backend"
build = "npm install && npm run build"
start = "npm start"

[frontend]
working_directory = "frontend"
build = "npm install && npm run build"
start = "npx serve -s dist"  # Optional if Coolify serves static files

[general]
framework = "node"  # Specify the framework explicitly (e.g., Node.js for backend/frontend)
