providers = ["node"]

[fases.build]
cmds = [
  "cd backend && npm install && npm run build",
  "cd frontend && npm install && npm run build"
]

[inicio]
dependsOn = ["build"]
cmd = [
  "cd backend && npm run start &",    # Run backend in the background
  "cd frontend && npm run preview -- --port 5173 &"   # Run frontend in the background as well
]

[variables]
PORT = "3000"
