providers = ["node"]

[phases.build]
commands = [
  "cd backend && npm install && npm run build",
  "cd frontend && npm install && npm run build"
]

[phases.start]
dependsOn = ["build"]
commands = [
  "cd backend && npm run start &",    # Run backend in the background
  "cd frontend && npm run preview -- --port 5173 &"   # Run frontend in the background as well
]

[variables]
PORT = "3000"
