[backend]
working_directory = "backend"
build = "npm install && npm run build"
start = "npm start"

[frontend]
working_directory = "frontend"
build = "npm install && npm run build"
# Remove the start command if using Coolify's static site option
start = "npx serve -s dist"
