# Specify build and run commands for backend and frontend separately
[phases.build]
commands = [
  "cd backend && npm install && npm run build",
  "cd frontend && npm install && npm run build"
]

[phases.start]
commands = [
  "cd backend && npm run start",
  "cd frontend && npm run preview -- --port 5173"
]

# Specify the ports if needed
[variables]
PORT = "3000" # Change to your backend's port if necessary
