providers = ["node"]

[phases.build]
commands = [
  "cd backend && pnpm run build",
  "cd frontend && pnpm run build"
]

[phases.start]
commands = [
  "cd backend && pnpm run start",
  "cd frontend && pnpm run preview -- --port 5173"
]

[variables]
PORT = "3000"