providers = ["node"]  # Explicitly specify the provider

[backend]
working_directory = "backend"
build = "npm install && npm run build"  # Adjust as needed for your backend
start = "npm start"

[frontend]
working_directory = "frontend"
build = "npm install && npm run build"  # Vite build command
start = "npx serve -s dist"             # Optional for static sites
