[provider]
type = "node"

[phases.build]
commands = [
  "cd backend && npm install && npm run build",
  "cd frontend && npm install && npm run build"
]

[phases.start]
commands = [
  "cd backend && npm run start",
  "cd frontend && npm run preview -- --port 5173"
]

[variables]
PORT = "3000"
